config:
  main-app-eu-west-2-locations-db:db_password:
    secure: AAABAOqW/o5XedxaqlAsgcz/5OJWCxEGdLK+1X/B4w5hnqj2qix1+PzSKJXmhYDfZkDTYq1T844kU23ZPZEW93q8vlBV3S1QPifq
  main-app-eu-west-2-locations-db:environment: dev-1
