version: '2.26'
services:
  locations-api:
    build:
      context: .
      target: release_locations_api
    depends_on: 
      - locations-db
    ports:
      - "3000:3000"
  locations-db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: locations-db
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"
    restart: always

volumes:
  db_data:
    driver: local